server:
  port: 8080
  servlet:
    context-path: /
springs:
#------------------配置redis start-------------------
  redis:
    database: 1 #redis数据库索引(默认为0)
    host: 47.104.19.44 #redis服务器地址
    port: 6379 #redis服务器端口
    password: 123 #密码
    cluster:
      nodes: 47.104.19.44:7001,47.104.19.44:7002,47.104.19.44:7003,47.104.19.44:7004,47.104.19.44:7005,47.104.19.44:7006
    pool:
      max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10 # 连接池中的最大空闲连接
      min-idle: 7 # 连接池中的最小空闲连接
    timeout: 5000 # 连接超时时间（毫秒）
    commandTimeout: 5000
    maxAttempts: 10000 #重试时间

#------------------配置redis end---------------------
spring:
#------------------模板引擎 start--------------------
#模板引擎配置路径
  thymeleaf:
    cache: false #关闭缓存及时刷新
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
#--------------------模板引擎 end--------------------

#-------------------配置支持热部署 start------------------
  devtools:
    restart:
      enabled: true #热部署生效
      additional-paths: src/main/java #设置重启的目录，添加哪个目录的文件需要restart
#---------------------配置支持热部署 start-------------------

#---------------------配置数据源 start---------------
#使用Mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/yepao
    username: root
    password: 123
    driverClassName: com.mysql.jdbc.Driver
#连接池的配置信息
    initialSize: 5 #初始化大小
    minIdle: 5 #最小
    maxActive: 20 #最大
    maxWait: 60000
#配置多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
#配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
# 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
    validationQuery: SELECT 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
#打开PSCache,别且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
#配置监控统计的filters，去掉后监控界面无法sql无法统计，‘wall’用于防火墙
    filters: stat,wall,log4j
#通过connectionProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
# 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
#---------------------配置数据源 end-----------------

#------------------配置redis start-------------------

#---------------------配置mybatis及其分页插件 start----------------

#--------------------- 配置mybatis及其分页插件 end----------------